client/package-lock.json, client/package.json, client/src/components/ui/label.tsx, client/src/components/ui/textarea.tsx, client/src/layouts/dashboard-layout.tsx.tsx, client/src/main.tsx, client/src/views/NewEvent.tsx
This PR adds the new event page
=> layout[New event}: Add New Event Page;

client/src/components/Navbar.tsx, client/src/views/NewEvent.tsx
This PR adds responsive tweaks to New Event page
=> layout[New Event]: Add Responsive tweaks;

client/src/views/NewPost.tsx
This PR adds the new post page
=> layout[New Post]: Add new post page;

client/src/views/Dashboard.tsx, client/src/views/Profile.tsx
=> layout[Profile]: Add responsive tweaks;

client/src/views/NewEvent.tsx
This PR adds input for organizer.
=> fix[NewEvent]: Add input for organizer;

client/src/views/NewTimeLine.tsx
=> fix[NewTimeline]: Add tag input;

client/package-lock.json, client/package.json, client/src/components/EventRegister.tsx, client/src/components/ui/dialog.tsx, client/src/components/ui/radio-group.tsx
This PR adds the event register input dialog
=> layout[EventRegister]: Add Event Register Input Dialog;

client/package-lock.json, client/package.json, client/src/components/EventRegister.tsx, client/src/components/Navbar.tsx, client/src/components/ui/dialog.tsx, client/src/components/ui/radio-group.tsx, client/src/layouts/dashboard-layout.tsx.tsx, client/src/main.tsx, client/src/views/Dashboard.tsx, client/src/views/NewEvent.tsx, client/src/views/NewPost.tsx, client/src/views/NewTimeLine.tsx, client/src/views/Profile.tsx
This PR will add the first features of all contributors. Including second feature of Samruddhi2405/layout/event-register-form
=> feat[First release]: Add first features of contributors;

client/src/data/eventData.json, client/src/views/Dashboard.tsx, client/src/views/NewPost.tsx
=> layout & fix[Events, NewPost]: Add Events, Fix Post button;

client/src/data/postData.json, client/src/views/Dashboard.tsx, client/src/views/NewPost.tsx
=> layout[Posts tab]: Add posts tab;

client/src/components/Navbar.tsx, client/src/layouts/dashboard-layout.tsx.tsx, client/src/layouts/protect-route.tsx, client/src/main.tsx, client/src/views/Landing.tsx, client/src/views/NewEvent.tsx, client/src/views/NewPost.tsx, client/src/views/NewTimeLine.tsx, client/src/views/Profile.tsx
This PR introduce some general fixes in responsiveness and route protection.
=> fix[First release]: Enhance Responsiveness; Fix route protection;

client/src/main.tsx, client/src/views/User1.tsx
=> build[User]: Add User Profile page;

client/src/components/Navbar.tsx, client/src/layouts/dashboard-layout.tsx.tsx, client/src/main.tsx, client/src/views/NewPost.tsx, client/src/views/NewTimeLine.tsx, client/src/views/Profile.tsx
This PR will Integrate the second features of the contributors which includes event register dialog, user profile page, Events tab, fix for the post button and posts tab. This PR addresses issue #31
=> feat & release[Second release]: Integrate second features of contributors to master;

client/src/views/NewPost.tsx
This PR adds the tag user input
=> chore[NewPost]: Add Tag User input;

client/src/data/postData.json, client/src/views/Dashboard.tsx
This PR adds tag button and reply button on post
=> build[Posts]: Add Tagged People and reply button;

client/src/components/ui/badge.tsx, client/src/main.tsx, client/src/views/InitiateProfileFirst.tsx
This PR adds initiate profile first page.
=> build[InitiateProfileFirst]: Add Initiate Profile First page;

client/package-lock.json, client/package.json, client/src/components/ReplyDialogTrigger.tsx, client/src/components/ui/scroll-area.tsx, client/src/data/replyData.json, client/src/layouts/dashboard-layout.tsx.tsx
=> build[ReplyDialog]: Add Reply Dialog;

client/src/layouts/dashboard-layout.tsx.tsx
This PR adds the search dialog
=> build[Search Dialog]: Add Search Dialog;

client/src/main.tsx, client/src/views/InitiateProfileSecond.tsx
This PR adds Initiate Profile Second Page.
=> build[InitiateProfileSecond]: Add Initiate Profile Second page;

client/src/components/EventCard.tsx, client/src/components/EventRegister.tsx, client/src/components/Navbar.tsx, client/src/components/PostCard.tsx, client/src/components/SearchDialogTrigger.tsx, client/src/components/TimelineCard.tsx, client/src/data/postData.json, client/src/layouts/dashboard-layout.tsx.tsx, client/src/main.tsx, client/src/types/types1.ts, client/src/views/Dashboard.tsx, client/src/views/InitiateProfileFirst.tsx, client/src/views/InitiateProfileSecond.tsx, client/src/views/Profile.tsx, client/src/views/User.tsx
This PR adds Minor bug fixes for 3rd feature integration to be merged into the master branch. The fixes are as follows
1. Colors on light/dark mode in event cards.
2. Encapsulate Event card and Post card.
3. Encapsulate Timeline card.
4. Fix reply button Alignment on posts card.
5. Implement event register from local branch "sam/layout/event-register-form".
6. Add Domains and Interests Card on self-profile.
7. Fix Domains and Interests Card on Public User Profile.
8. Fix Buttons, title and layout in Initiate-profile First.
9. Fix vertical layout in Initiate-profile Second.
10. Fix Search Input/Button layout on left sidebar.
11. Change filename User1 -> User.
12. Add Drawer for event register trigger.
13. Fix margins on Public User Profile.
14. Add Socials card on Public User Profile.
15. …
=> fix[Third release]: Add bug fixes and enhancements for 3rd feature integrations;

client/package-lock.json, client/package.json, client/src/components/ui/toast.tsx, client/src/components/ui/toaster.tsx, client/src/components/ui/use-toast.ts, client/src/context/UserContext.tsx, client/src/layouts/root-layout.tsx, client/src/main.tsx, client/src/views/InitiateProfileFirst.tsx, client/src/views/InitiateProfileSecond.tsx, client/src/views/Profile.tsx, server/controllers/profileControllers.js, server/index.js, server/models/index.js, server/models/profileSchema.js, server/package-lock.json, server/package.json, server/routes/profileRoutes.js
This PR adds the profile model and it's corresponding CRUD operations.
=> feat[Profile Model]: Add Profile model and related CRUD ops;

server/controllers/postControllers.js, server/controllers/replyControllers.js, server/models/replySchema.js, server/routes/postRoutes.js, server/routes/replyRoutes.js
This PR adds replies Controllers.
=> feat[Backend/Replies]: Add Reply Model and related CRD ops.

server/controllers/eventControllers.js, server/models/eventSchema.js, server/routes/eventRoutes.js
=> feat[Backend/Events]: Add Event controllers;

client/src/components/EditProfileTriggers.tsx, client/src/components/EventCard.tsx, client/src/components/EventRegister.tsx, client/src/components/PostCard.tsx, client/src/components/ReplyDialogTrigger.tsx, client/src/components/TimelineCard.tsx, client/src/context/UserContext.tsx, client/src/hooks/useEvent.tsx, client/src/hooks/usePost.tsx, client/src/hooks/useTimeline.tsx, client/src/views/Dashboard.tsx, client/src/views/NewEvent.tsx, client/src/views/NewPost.tsx, client/src/views/NewTimeLine.tsx, client/src/views/Profile.tsx, client/src/views/User.tsx, server/controllers/postControllers.js, server/controllers/profileControllers.js, server/controllers/replyControllers.js, server/controllers/timelineControllers.js, server/models/eventSchema.js, server/models/postSchema.js, server/models/profileSchema.js, server/models/replySchema.js, server/models/timelineSchema.js, server/routes/profileRoutes.js
This is a major fix and refactor changes which increases more application and code reuseability.
=> PR: Refactor and bug fixes;
